Update install.py
Fixed syntax error due to missing parenthesis

```
SWAP set...

Preparing...

  File "install.py", line 801
    preFlightsChecks.call(command, self.distro, command, command, 1, 0, os.EX_OSERR)
    ^
SyntaxError: invalid syntax
Oops, something went wrong...
```